db:
  username: catclubsystem
  password: 2010mainecoon2010
  host: ls-ad0ef4e184e7a556c4e988f165f81bdb159f5185.cpx4ifio97ko.us-east-1.rds.amazonaws.com
  port: 3306
  name: dbcatclubsystem
mongodb:
  username: amacoonservice
  password: 2010mainecoon2010
  #host: mongo
  host: amacoon.6g9ffc8.mongodb.net
  port: 27017
main.go  name: amacoon
server:
  port: 8080
openAI:
  key: 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
