db:
  username: catclubsystem
  password: 2010mainecoon2010
  host: ls-ad0ef4e184e7a556c4e988f165f81bdb159f5185.cpx4ifio97ko.us-east-1.rds.amazonaws.com
  port: 3306
  name: dbcatclubsystem
server:
  port: 8080
openAI:
  key: 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

